# Notebook 04: Classification Models & Zero-Leakage Pipeline Benchmarking
Evaluating 6 classification model families across both Stratified 5-Fold CV and Temporal split under 3 experimental configurations (Baseline, Metadata-Only, and Dialogue+Metadata).

In [1]:
import os, sys
from pathlib import Path
root = Path.cwd() if (Path.cwd() / 'configs').exists() else Path.cwd().parent
os.chdir(root)
if str(root / 'src') not in sys.path:
    sys.path.insert(0, str(root / 'src'))
import pandas as pd
from bechdel.models.classification import run_classification_experiments

tier2_df = pd.read_parquet('data/processed/tier2_features.parquet')
clf_res = run_classification_experiments(tier2_df)
summary = clf_res['summary_table']
print(f'Top 5 models by cross-validated F1 score:')
display(summary[['experiment', 'model', 'feature_set', 'cv_accuracy', 'cv_precision', 'cv_recall', 'cv_f1', 'cv_pr_auc', 'temp_f1']].head(8))

/Users/somya/Desktop/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/somya/Desktop/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/somya/Desktop/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/somya/Desktop/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/somya/Desktop/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/somya/Desktop/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/somya/Desktop/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

/Users/somya/Desktop/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/somya/Desktop/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/somya/Desktop/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/somya/Desktop/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/somya/Desktop/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/somya/Desktop/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/somya/Desktop/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

Top 5 models by cross-validated F1 score:

,experiment,model,feature_set,cv_accuracy,cv_precision,cv_recall,cv_f1,cv_pr_auc,temp_f1
12,Exp3_Metadata_Plus_Dialogue,NaiveBayes,dialogue+metadata,0.7376,0.7580,0.6364,0.6919,0.7833,0.5660
10,Exp3_Metadata_Plus_Dialogue,LogisticRegression,dialogue+metadata,0.7203,0.7102,0.6684,0.6887,0.7858,0.5185
2,Exp2_Metadata_Only,LogisticRegression,metadata,0.6931,0.6567,0.7059,0.6804,0.7111,0.6667
15,Exp3_Metadata_Plus_Dialogue,RandomForest,dialogue+metadata,0.7302,0.7566,0.6150,0.6785,0.7885,0.5714
14,Exp3_Metadata_Plus_Dialogue,SVM,dialogue+metadata,0.7277,0.7484,0.6203,0.6784,0.7618,0.5455
11,Exp3_Metadata_Plus_Dialogue,KNN,dialogue+metadata,0.7104,0.7160,0.6203,0.6648,0.7467,0.5283
16,Exp3_Metadata_Plus_Dialogue,HistGradientBoosting,dialogue+metadata,0.6980,0.6857,0.6417,0.6630,0.7701,0.5926
13,Exp3_Metadata_Plus_Dialogue,DecisionTree,dialogue+metadata,0.6856,0.6667,0.6417,0.6540,0.7227,0.6038

In [2]:
# Compare headline comparison: Metadata-Only vs Dialogue+Metadata
lr_comp = summary[summary['model'] == 'LogisticRegression']
display(lr_comp[['experiment', 'feature_set', 'cv_f1', 'cv_pr_auc', 'cv_roc_auc', 'temp_f1']])

,experiment,feature_set,cv_f1,cv_pr_auc,cv_roc_auc,temp_f1
10,Exp3_Metadata_Plus_Dialogue,dialogue+metadata,0.6887,0.7858,0.7660,0.5185
2,Exp2_Metadata_Only,metadata,0.6804,0.7111,0.7398,0.6667